[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings=["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
# /home/sneha/solidity-foundry-code/foundry-fundme-contract/lib/chainlink-brownie-contracts/contracts